name: RefreshScript

on:
  workflow_dispatch:
  # Optional: also refresh daily at 00:05 UTC (staggered)
  schedule:
    - cron: "5 0 * * *"

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump hash comment
        run: |
          f=".github/workflows/RefreshScript.yml"
          ts="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          if grep -q '^# trigger:' "$f"; then
            sed -i "s|^# trigger:.*|# trigger: ${ts}|" "$f"
          else
            printf "\n# trigger: %s\n" "$ts" >> "$f"
          fi

      - name: Commit and push
        run: |
          ts="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/RefreshScript.yml
          git commit -m "Refresh JSON trigger ${ts}" || echo "No changes"
          git push
