name: RefreshClones (APK Trigger)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # optional: once daily at 09:00 UTC

jobs:
  trigger-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure triggers directory
        run: mkdir -p .triggers

      - name: Write APK trigger (one line: RUN_ID)
        run: |
          echo "${{ github.run_id }}" > .triggers/apk.trigger
          echo "time=${{ github.run_number }} @ ${{ github.run_id }} @ ${{ github.run_attempt }}" >> .triggers/apk.meta

      - name: Commit and push
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add .triggers/apk.trigger .triggers/apk.meta
          git commit -m "APK trigger: run_id ${{ github.run_id }}"
          git push
