name: RefreshClones (APK trigger)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trigger-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write trigger file
        run: |
          mkdir -p triggers
          {
            echo "RUN_ID=${GITHUB_RUN_ID}"
            echo "RUN_NUMBER=${GITHUB_RUN_NUMBER}"
            echo "TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            echo "COMMIT_SHA=${GITHUB_SHA}"
          } > triggers/apk.trigger

      - name: Commit and push trigger
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add triggers/apk.trigger
          git commit -m "APK trigger: run $GITHUB_RUN_ID at $(date -u +%F\ %T) UTC" || echo "No changes to commit"
          git push
