name: RefreshScript (JSON trigger)

on:
  workflow_dispatch: {}
  # Optional: run on a schedule too
  # schedule:
  #   - cron: "15 */6 * * *"  # every 6 hours at :15

permissions:
  contents: write

jobs:
  trigger-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare trigger file
        run: |
          mkdir -p triggers
          echo "$(date -u +%FT%TZ) RUN_ID=${GITHUB_RUN_ID}" > triggers/json.trigger

      - name: Commit trigger
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add triggers/json.trigger
          git commit -m "JSON trigger ${GITHUB_RUN_ID}" || echo "No changes to commit"

      - name: Push
        run: |
          git push

