name: RefreshScript
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trigger-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write JSON trigger token
        run: |
          mkdir -p .triggers
          echo "{\"token\":\"json-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}\",\"run_id\":\"${GITHUB_RUN_ID}\",\"time\":\"${{ github.event.repository.updated_at || github.run_started_at }}\"}" > .triggers/json.json

      - name: Commit and push trigger
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .triggers/json.json
          git commit -m "JSON trigger ${GITHUB_RUN_ID}"
          git push
