name: APK Refresh Trigger

on:
  workflow_dispatch:
  # Optional: uncomment to auto-trigger every 12 hours
  # schedule:
  #   - cron: "0 */12 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Emit APK trigger
        run: |
          echo "APK trigger at $(date -u +%FT%TZ)"
