name: Refresh JSON trigger

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 */12 * * *"  # optional: every 12 hours, offset for separation

permissions:
  contents: write

jobs:
  bump-json-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update JSON trigger file
        run: |
          mkdir -p .triggers
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .triggers/json.trigger
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .triggers/json.trigger
          git commit -m "Trigger JSON at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
