name: JSON Task
on:
  workflow_dispatch:

jobs:
  run-json-task:
    runs-on: ubuntu-latest
    steps:
      - name: Run JSON job on Termux
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TERMUX_SSH }} "bash automation.sh json"
