name: Refresh JSON Only

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run JSON-only update
        run: bash autoinstall.sh --json
