name: Refresh JSON Only
on:
  workflow_dispatch:

jobs:
  sync-json:
    name: Sync JSON on Termux
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure script is executable
        run: chmod +x ./sync_apps_and_json.sh

      - name: Run JSON sync only
        env:
          SKIP_APKS: "true"
        run: |
          tsu -c "SKIP_APKS=true ${GITHUB_WORKSPACE}/sync_apps_and_json.sh"
