name: RefreshScript

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-run-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump RUN_TOKEN in this workflow file
        run: |
          set -euo pipefail
          FILE=".github/workflows/RefreshScript.yml"
          TOK="$(date -u +%s)"
          perl -0777 -pe 's/(^|\n)\s*RUN_TOKEN:\s*\K\d+/'"$TOK"'/' -i "$FILE" || true
          if ! grep -qE '^\s*RUN_TOKEN:\s*[0-9]+' "$FILE"; then
            printf '\n# Device trigger token\nRUN_TOKEN: %s\n' "$TOK" >> "$FILE"
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "RefreshScript trigger $TOK" || echo "No changes to commit"
          git push
# Device trigger token
RUN_TOKEN: 0
