name: RefreshScript (JSON Trigger)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"  # optional schedule

jobs:
  trigger-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure triggers directory
        run: mkdir -p .triggers

      - name: Write JSON trigger (one line: RUN_ID)
        run: |
          echo "${{ github.run_id }}" > .triggers/json.trigger
          echo "time=${{ github.run_number }} @ ${{ github.run_id }} @ ${{ github.run_attempt }}" >> .triggers/json.meta

      - name: Commit and push
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add .triggers/json.trigger .triggers/json.meta
          git commit -m "JSON trigger: run_id ${{ github.run_id }}"
          git push
