name: JSON Refresh Trigger

on:
  workflow_dispatch:
  # Optional: uncomment to auto-trigger daily at 03:00 UTC
  # schedule:
  #   - cron: "0 3 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Emit JSON trigger
        run: |
          echo "JSON trigger at $(date -u +%FT%TZ)"
