name: RefreshScript

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: self-hosted
    steps:
      - name: Trigger Termux JSON refresh
        run: |
          tsu -c "bash ~/.termux/boot/refresh.sh json"
