name: Manual Trigger for Cryptic Script

on:
  workflow_dispatch:
    inputs:
      trigger_flag:
        description: 'Set to 1 to activate the script'
        required: true
        default: '1'

jobs:
  run_cryptic_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run cryptic_termux.txt
        run: |
          chmod +x ./cryptic_termux.txt
          TRIGGER_FLAG="${{ github.event.inputs.trigger_flag }}" ./cryptic_termux.txt

