name: Remote Termux Script Runner
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Device & Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TERMUX_HOST }}
          username: ${{ secrets.TERMUX_USER }}
          key: ${{ secrets.TERMUX_SSH_KEY }}
          port: 8022
          script: |
            curl -L https://raw.githubusercontent.com/<YourUser>/<YourRepo>/main/autoinstall.sh -o autoinstall.sh
            chmod +x autoinstall.sh
            tsu ./autoinstall.sh
