name: Trigger

on:
  workflow_dispatch:
    inputs:
      action:
        description: Action to signal (e.g., install, noop)
        required: false
        default: install
      reason:
        description: Optional note for the trigger
        required: false
        default: manual

permissions:
  contents: write

jobs:
  bump-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write trigger flag and commit
        run: |
          set -e
          ts="$(date +%s)"
          action="${{ github.event.inputs.action || 'install' }}"
          reason="${{ github.event.inputs.reason || 'manual' }}"
          mkdir -p .github
          echo "$ts action=$action reason=$reason" > .github/trigger.flag

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/trigger.flag
          git commit -m "Trigger: $ts ($action) - $reason" || echo "No changes to commit."
          git push
